### ISSUE TITLE
How to run prettydiff after installation via biddle?

### ISSUE THREAD

**Issue by v3ss0n** [prettydiff/biddle#35]

**Comment by prettydiff** [comment]
There are two options:

1. Move into the directory of the installed application and run that application locally according to its documentation.
2. Add the application to the environment path so that it is globally available as a command: `biddle global prettydiff`.

If those don't work or could use some simplification please let me know.  biddle is very new and largely demanding of input from users.  **By the way, thank you for taking the time to try this out.**

**Comment by v3ss0n** [comment]
thank you very much for your response. i am trying it to build a beautifier for vscode , like atom-beautify since , vscode formattor is very lacking compare to atom-beautify.

i got to do it by going into prettydiff and running nodelocal. a bit hard. i will need quite a lot of help. Should i ask here or are there any channels?

**Comment by prettydiff** [comment]
Pretty Diff will use the node-local.js file for all command line operations.  It is how Atom Beautify uses Pretty Diff.  It should be as simple as building out your options and sending that criteria to node-local.js.

Why don't you describe in as much detail as possible what you are trying to do?   I can then help you find the fastest solution.

**Comment by v3ss0n** [comment]
thank you , i am new to doing extension , i am trying to run it like this 

``` javascript

// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
var vscode = require('vscode');
var prettydiff = require("./prettydiff")

var fs = require('fs')

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
function activate(context) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "vscode-prettydiff" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    var prettyDiff = vscode.commands.registerCommand('extension.prettyDiff', function () {
        // The code you place here will be executed every time your command is executed
        // Display a message box to the user
        var editor = vscode.window.activeTextEditor;
        if (!editor) {
            return; // No open text editor
        }
        var path = editor.document.uri.fsPath;
        console.log(editor)
        console.log(editor.document)

       var source = fs.readFile(path, 'utf8', function (err, data) {
            if (err) {
                return console.log(err);
            }
            return data;
        });
        var args = {
            source: source,
            mode: "beautify",
            lang: "auto",
        }

    });

    context.subscriptions.push(prettyDiff);
}
exports.activate = activate;

// this method is called when your extension is deactivated
function deactivate() {
}
exports.deactivate = deactivate;

```

**Comment by v3ss0n** [comment]
i think i should have just pass the path to node-local.js , and run in a fork ?

**Comment by v3ss0n** [comment]
it is written that :
```
Command line API for Prettydiff for local execution only.  This API is
not intended for execution as a service on a remote server.
```
should not be executed as a service?
